# Generated by Django 5.1.1 on 2024-10-08 11:56

from django.db import migrations


def insert_hardcoded_words(apps, schema_editor):
    Word = apps.get_model('anagram', 'Word')

    words = [
        'animal',
        'around',
        'backup',
        'banana',
        'bright',
        'castle',
        'charge',
        'choice',
        'circle',
        'danger',
        'design',
        'energy',
        'family',
        'friend',
        'garden',
        'global',
        'health',
        'height',
        'inside',
        'little',
        'mother',
        'nature',
        'orange',
        'people',
        'planet',
        'public',
        'return',
        'school',
        'system',
        'travel',
        'yellow',
        'listen',
        'silent',
        'enlist',
        'tinsel',
        'inlets',
        'rescue',
        'secure',
        'crates',
        'reacts',
        'traces',
        'caters',
        'caster',
        'recast',
        'earths',
        'haters',
        'hearts',
        'shares',
        'shears',
        'alerts',
        'alters',
        'artels',
        'estral',
        'salter',
        'staler',
        'talent',
        'latent',
        'garden',
        'danger'
    ]

    for word in words:
        Word.objects.create(value=word)


class Migration(migrations.Migration):

    dependencies = [
        ('anagram', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_hardcoded_words),
    ]
